name: Update Submodules

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'  # Runs every 2 hours

jobs:
  update_submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Update submodules
        run: |
          # Configure git credentials
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          
          # Set merge strategy globally
          git config --global pull.rebase false
          
          # For each submodule, pull the latest commit from the 'main' branch
          git submodule foreach 'git config pull.rebase false && git pull origin main || echo "Pull failed for this submodule, continuing..."'
          
          # Stage any updated submodule pointers
          git add .
          
          # If there are changes, commit them
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "chore: Update submodule pointers"
            git push origin HEAD:main
          else
            echo "No updates in submodules."
          fi